# Define the Cloud Build pipeline steps
steps:
  # Step 1: Check out the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', 'https://github.com/kaitech-corp/$REPO_NAME', '/workspace/$SHORT_SHA']
    dir: '/workspace/$SHORT_SHA'
  
  # Step 2: Fetch unshallow/full history from repository 
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |      
  #       pwd
  #       cd /workspace/$SHORT_SHA
  #       ls
  # Step 3: Check if the changes include JSON files and save them to storage
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the latest changes from the remote repository

        # Get a list of modified JSON files in the "api" directory
        modified_files=$(git diff --name-only HEAD~1 HEAD | grep '^api/.*\.json$' | sed 's/^api\///')
        if [ -n "$modified_files" ]; then
          echo 'Modified JSON files detected.'

          # Loop through the modified files and copy them to the Cloud Storage bucket
          for file in $modified_files; do
            gsutil cp /workspace/$SHORT_SHA/api/$file gs://api-project-371618.appspot.com/$file
            gsutil acl ch -u AllUsers:R gs://api-project-371618.appspot.com/$file
          done
        else
          echo 'No modified JSON files detected.'
        fi
    env:
      - 'modified_files=$(git diff --name-only HEAD~1 HEAD | grep \''^api/.*\.json$\'' | sed \''s/^api\///\'')'
